# -*- coding: utf-8 -*-
"""Asssignment.five.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ji9TRbjdaPwhrR8E3IY3chJOsa9aRyg
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

url="https://islamqa.info/en/answers/128927/it-is-essential-to-acquire-and-take-possession-of-items-before-selling-them"
page=requests.get(url)
soup=BeautifulSoup(page.content, "html5")
title=soup.find(class_="title is-4 is-size-5-touch").text.replace("\n","")
print(title)
question=soup.find(class_="single_fatwa__question text-justified").text.replace("\n","")
print(question)
answer=soup.find(class_="single_fatwa__answer").text.replace("\n","")
print(answer)
questionNo=soup.find(class_="subtitle has-text-weight-bold has-title-case cursor-pointer tooltip").text.replace("\n","")
print(questionNo)

data=[[url, title, question, answer, questionNo]]
data
df=pd.DataFrame(data,columns=["Url", "Title", "Question", "Answer", "QuestionNo"])
df
df.to_csv("Assignment_5.csv")

"""# New Section"""